name: Python Tests

on:
  push:
    branches:
      - main   # runs tests when you push to main branch
  pull_request: # also runs tests when someone makes a PR into main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"   # You can change this version if needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install pytest

      - name: Run tests
        run: |
          pytest
